/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.interview;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;
import javax.swing.UIManager.*;
import static javax.management.remote.JMXConnectorFactory.connect;

/**
 *
 * @author diyohan
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        last_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        role_field = new javax.swing.JList<>();
        submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        manager = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(550, 0), new java.awt.Dimension(550, 0), new java.awt.Dimension(550, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("S-Squared Enterprises Personnel System");
        setBounds(new java.awt.Rectangle(240, 240, 240, 240));
        setName("register"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 600));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Employee ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 76, -1));

        id_field.setText("Enter Text");
        id_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(id_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 170, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("  First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 80, 20));

        name_field.setText("Enter Text");
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 170, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("    Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 80, -1));

        last_field.setText("Enter Text");
        last_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(last_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 170, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("             Roles:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 76, -1));

        role_field.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Accounting", "Analyst", "Director", "IT", "Sales", "Support" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        role_field.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                role_fieldCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        role_field.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                role_fieldValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(role_field);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 170, 64));

        submit.setText("Save");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Add New Employee");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 210, 47));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("    Manager:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 91, 25));

        manager.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        manager.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                managerItemStateChanged(evt);
            }
        });
        manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerActionPerformed(evt);
            }
        });
        getContentPane().add(manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 171, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Populate the combo box
    private void populate() {
    	 try {
     		
    		manager.addItem("No Manager");
     		Database dm = new Database();
     		List <String> response = dm.manInfo();
     		for (int i = 0; i < response.size(); i++) {
     		  
     		    manager.addItem(response.get(i));
     		}
     	} catch(Exception e) {
     		System.out.println("Unable to fetch manager data");
     	}
    	
    }
    
    private void id_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_fieldActionPerformed

    private void last_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_fieldActionPerformed

    private void role_fieldCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_role_fieldCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_role_fieldCaretPositionChanged

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
    	
        try{
        
     
        //Get info from the submission
        String first_name = name_field.getText();
        String last_name =  last_field. getText();
        String  id  =  id_field.getText(); 
        String superName = "";
        if(manager.getSelectedItem() != null) {
        	superName = manager.getSelectedItem().toString();
        }
        //Flag to identify supervisors
        String supervisor = "no";
        //System.out.println("Name Check " + first_name);
        //System.out.println("Last Name" + last_name);
        //System.out.println(" Id " + id);
        var builder = new StringBuilder();
        String dir = "Director";
        //Turn the roles into a mutable string
            List<String> indices =  role_field.getSelectedValuesList();
            if (indices.contains(dir)){
               supervisor = "yes";
               System.out.println(first_name + " "+ last_name +" is "+ "Director "+ supervisor);
        }
            for(int i=0; i < indices.size(); i++){
            System.out.println("Employee have this roles" + indices.get(i));
            if (i+1 == indices.size()){
                builder.append(indices.get(i)).append(".");
            }
            else{
                builder.append(indices.get(i)).append(",");
            }
            }
        
        System.out.println("This is the roles " + builder+ "Is he a employee?" + supervisor);
        //update the database information
        Database db = new Database();
        db.addEmployee(id,first_name,last_name,builder.toString(),supervisor,superName);
        
        //Update manager info
        if(indices.contains(dir)) {
        	populate();
        }
        dispose();
        Home home = new Home();
        home.setVisible(true);
        }
        
        catch(Exception e){
            System.out.println("Employee was not saved");
        }
    }//GEN-LAST:event_submitActionPerformed
    
    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_managerActionPerformed

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fieldActionPerformed

    private void role_fieldValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_role_fieldValueChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_role_fieldValueChanged

    private void managerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_managerItemStateChanged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_managerItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Home home = new Home();
        home.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Ocean look and feel */
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows XP".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField id_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last_field;
    private javax.swing.JComboBox<String> manager;
    private javax.swing.JTextField name_field;
    private javax.swing.JList<String> role_field;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
